<?php
    @ini_set('max_execution_time',0);

    $_tags = new Mage_Tag_Block_Product_List();

    $keys = array();
    foreach ($_tags->getTags() as $tag) {
        $keys[] = trim($tag->getName());
    }

    $results = array();

    // foreach($keys as $key) {
    $key = implode(" ", $keys);
    $key=urlencode($key);
    $key=str_replace("%20","+",$key);
    if($key != ""){
        $searchResult=file_get_contents("http://www.youtube.com/results?search_type=videos&search_query=".$key."&page=1");

        if(strpos($searchResult,"/watch?v=")!=FALSE) {
            preg_match_all("/href=\"\/watch\?v=([^\"]*)\"/sU",$searchResult,$matches);
            $resultMovies = array_unique($matches[1]);

            foreach($resultMovies as $movielink) {
                $results[] = "http://www.youtube.com/v/".trim($movielink)."\r\n";
                if (count($results)==4) {
                    break;
                }
            }
        }
    }
?>



<div class="tegs-video-slider">
    <?php echo $this->getChildHtml('upsell_products') ?>
    <?php echo $this->getChildHtml('product_additional_data') ?>
    <?php

    ?>
    <div id="product-tags">
        Product Tags:

        <?php foreach($_tags->getTags() as $tag):?>
            <?php echo $tag->getName() ?>
        <?php endforeach;?>
    </div>



    <div class="slider">
        <ul>
    <?php foreach($results as $result): ?>


            <li><iframe width = "560" height = "315" src = "<?php echo $result ?>" frameborder = "0" allowfullscreen ></iframe ></li>

    <?php endforeach; ?>
        </ul>
    </div>
</div>


<!--<script type="text/javascript" src="http://code.jquery.com/jquery-latest.min.js"></script>-->
<script type="text/javascript">
    $(document).ready(function() {
        $(".slider").each(function () { // обрабатываем каждый слайдер
            var obj = $(this);
            $(obj).append("<div class='nav'></div>");
            $(obj).find("li").each(function () {
                $(obj).find(".nav").append("<span rel='"+$(this).index()+"'></span>"); // добавляем блок навигации
                $(this).addClass("slider"+$(this).index());
            });
            $(obj).find("span").first().addClass("on"); // делаем активным первый элемент меню
        });
    });
    function sliderJS (obj, sl) { // slider function
        var ul = $(sl).find("ul"); // находим блок
        var bl = $(sl).find("li.slider"+obj); // находим любой из элементов блока
        var step = $(bl).width(); // ширина объекта
        $(ul).animate({marginLeft: "-"+step*obj}, 500); // 500 это скорость перемотки
    }
    $(document).on("click", ".slider .nav span", function() { // slider click navigate
        var sl = $(this).closest(".slider"); // находим, в каком блоке был клик
        $(sl).find("span").removeClass("on"); // убираем активный элемент
        $(this).addClass("on"); // делаем активным текущий
        var obj = $(this).attr("rel"); // узнаем его номер
        sliderJS(obj, sl); // слайдим
        return false;
    });
</script>
<style type="text/css">
    .slider {
        z-index: 9;
        width: 560px;

        overflow: hidden;
        margin: 0 auto;
        position: relative;
    }
    .slider ul,
    .slider li {
        padding: 0;
        margin: 0;
        list-style-type: none;
    }
    .slider ul {
        width: 9999px;
    }
    .slider ul li {
        list-style-type: none;
        float: left;
        width: 560px;

    }
    .slider .nav {
        position: absolute;
        left: 15px;
        bottom: 12px;
    }
    .slider .nav span {
        opacity: 0.9;
        background: #fff;
        margin: 0 8px 0 0;
        width: 16px;
        height: 16px;
        border-radius: 8px;
        cursor: pointer;
        overflow: hidden;
        display: block;
        float: left;
        box-shadow: 0 1px 2px #000;
    }
    .slider .nav span.on {
        background: #3399cc;
    }
</style>